#!/bin/sh

set -e

case "$1" in
    install|upgrade)
	if dpkg --compare-versions "$2" le "1.7"; then
		for d in /etc/cron.d /etc/network/if-*.d /etc/ppp/ip-*.d ;do
			if [ -f $d/vnstat ]; then
				echo "Removing $d/vnstat"
				rm -f  $d/vnstat
			fi
		done
	fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
